#!/usr/bin/env bash
# This script prints "bad luck" every 4th generation, "good luck" every 8th generation and "Best School" if none

a=1

while [ $a -lt 11 ]
do
    if [[ $a == 4 ]]
    then
        echo "bad luck"
    elif [[ $a == 8 ]]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((a++))
done;
